# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01fd091b41de8dbe4abad2072c4d1a2197f4e2af975d1f65d8977e0b7033642330f0cd43ef0d2f60e26d724d32d8802f261446f0b471ff0d042ae4096aeb1063

test:
  secret_key_base: c68757e5d9bfbb81cf866bf9944e6517248dbf9b55bff896508ddf1fae526e8162fb34b9bd1a574a0eab96a94384cdab58238c4d7e28fc57ba96695caaecb4cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
